// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Error provides a mock function with given fields: endpoint, actionName, request, message
func (_m *Logger) Error(endpoint string, actionName string, request interface{}, message interface{}) {
	_m.Called(endpoint, actionName, request, message)
}
