version: '2.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: my-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=pam-es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/logs:/var/log/elasticsearch
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: my-kibana
    links:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/logs:/var/log/kibana/
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch