// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	entity "subscribetool/src/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAllSubscribers provides a mock function with given fields:
func (_m *Repository) GetAllSubscribers() ([]entity.Subscribers, error) {
	ret := _m.Called()

	var r0 []entity.Subscribers
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Subscribers, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Subscribers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Subscribers)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
